import axios from 'axios';
import * as actionTypes from './actionTypes';

import {signinLink, signupLink, updateProfileLink, flashcardsDecksLink} from '../../shared/endpoints';

//AUTH
const authStart = () => {
	return {
		type: actionTypes.AUTH_START,
	};
};

const authSuccess = (token, localId, name) => {
	return {
		type: actionTypes.AUTH_SUCCESS,
		token: token,
		localId: localId,
		name: name,
	};
};

const authFail = error => {
	return {
		type: actionTypes.AUTH_FAIL,
		error: error,
	};
};

export const logout = () => {
	localStorage.removeItem('token');
	localStorage.removeItem('expiresOn');
	localStorage.removeItem('localId');
	localStorage.removeItem('name');

	return {
		type: actionTypes.AUTH_LOGOUT,
	};
};

export const handleAuthTimeout = expirationTime => {
	return dispatch => {
		setTimeout(() => {
			dispatch(logout());
		}, expirationTime * 1000);
	};
};

//It's not even an action, but had to put this helper function somewhere
const authChangeUserProfile = (token, name) => {
	axios.post(updateProfileLink, {idToken: token, displayName: name});
};

const retrieveAsyncData = async (dispatch, getState) => {
	const state = getState();
	let decks = await axios
		.get(`${flashcardsDecksLink}/${state.auth.localId}.json?auth=${state.auth.token}`)
		.then(({data}) => {
			console.log(data);
			/*So
		Decks is an object of decks, that looks like this:
		decks: {
			animals: [{front: 'gato', back: 'cat'}],
			verbs: [
						{front: 'ser', back: 'to be'},
						{front: 'comer', back: 'eat'},
					]
		}
		Exaclty like FlashcardsDecks property of the state

		If you want to get this from firebase, you send request on the url in the axios, and you get back with an object
		of a name generated by firebase, and you cannot rely on this name!
		So you do Object.keys(data)[0] to get the value of this strange object
		and you assign this value to the decks object
		and voilà
		*/

			const tempDecks = data[Object.keys(data)[0]];
			return tempDecks;
		})

		.catch(err => console.log(err));
	console.log(decks);

	dispatch({
		type: actionTypes.RETRIEVE_DATA,
		decks: decks,
	});
};

export const auth = (email, password, isSignup, name = '') => {
	return dispatch => {
		dispatch(authStart());
		const authData = {
			email: email,
			password: password,
			returnSecureToken: true,
		};

		let url = signinLink;
		if (!isSignup) {
			url = signupLink;
		}
		axios
			.post(url, authData)
			.then(response => {
				const {
					data: {expiresIn, idToken, localId},
				} = response;
				const expiresOn = new Date(new Date().getTime() + expiresIn * 1000);
				localStorage.setItem('token', idToken);
				localStorage.setItem('expiresOn', expiresOn);
				localStorage.setItem('localId', localId);
				dispatch(authSuccess(idToken, localId));
				dispatch(handleAuthTimeout(expiresIn));
				if (name && name.trim() !== '') {
					authChangeUserProfile(idToken, name);
				}
				dispatch(retrieveAsyncData);
			})
			.catch(err => {
				dispatch(authFail(err.response.data.error));
			});
	};
};

// Flashcards
export const addDeck = deckName => {
	return {
		type: actionTypes.ADD_DECK,
		newDeck: deckName,
	};
};

export const deleteDeck = deckName => {
	return {
		type: actionTypes.DELETE_DECK,
		deckToDelete: deckName,
	};
};

export const pushCards = (deckName, cardsArray) => {
	return {
		type: actionTypes.PUSH_CARDS,
		deckToModify: deckName,
		cardsArray: cardsArray,
	};
};

export const deleteCard = (deckName, cardNumber) => {
	return {
		type: actionTypes.DELETE_CARD,
		deckToModify: deckName,
		cardToDelete: cardNumber,
	};
};

export const saveFlashcardsDataToDB = async (dispatch, getState) => {
	const state = getState();
	axios
		.delete(`${flashcardsDecksLink}/${state.auth.localId}.json?auth=${state.auth.token}`)
		.then(response => {
			axios
				.post(`${flashcardsDecksLink}/${state.auth.localId}.json?auth=${state.auth.token}`, {
					...state.flashcardsDecks,
				})
				.then(response => {})
				.catch(error => console.log(error)); //
		})
		.catch(error => console.log(error));
	dispatch({
		type: actionTypes.SAVE_DATA_TO_DB,
	});
};
